name: flutter_samples
description: samples for many implementation of flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  here_sdk:
    path: plugins/here_sdk
  bloc: ^6.1.1
  build_runner: ^1.10.1
  camera: ^0.7.0
  cloud_firestore: ^0.14.3
  cupertino_icons: ^0.1.3
  division: ^0.8.8
  english_words: ^3.1.5
  equatable: ^1.2.6
  firebase: ^7.3.2
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.2
  firebase_storage: ^5.0.1
  flare_flutter: ^2.0.6
  flutter_bloc: ^6.1.2
  flutter_mobx: ^1.1.0+2
  flutter_slidable: ^0.5.7
  google_fonts: ^1.1.0
  google_maps_flutter: ^1.0.6
  google_sign_in: ^4.5.4
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  hive_generator: ^0.7.1
  http: ^0.12.0
  hydrated_bloc: ^6.0.3
  image_picker: ^0.6.7+14
  json_serializable: ^3.4.1
  loadmore: ^1.0.4
  local_auth: ^0.6.3+2
  location: ^3.2.4
  mobx: ^1.2.1+2
  mobx_codegen: ^1.1.0+1
  onesignal_flutter: ^2.6.1
  path: ^1.7.0
  path_provider: ^1.6.27
  provider: ^4.3.2+3
  replay_bloc: ^0.0.1-dev.2
  rxdart: ^0.25.0
  shared_preferences: ^0.5.8
  shimmer: ^1.1.1
  sqflite: ^1.3.2+1
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/switch_daytime.flr
    - assets/Liquid_Loader.flr
    - assets/Loading.flr
    - assets/loading-animation-sun-flare.flr
    - assets/loading_success_error.flr
    - assets/images/google_logo.png
    - assets/data/users.json
    - assets/layer_photo.png
    - assets/dotsmall.png
    - assets/pin.png
    - assets/winner.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
